# 8QUEEN Problem

In [5]:
import numpy as np
global N
N = int(input())

5


## Checking for safe state if exist

In [6]:
def isSafe(board , row ,col ):
    for i in range(col):
        if board[row][i]==1:
            return False
    for i,j in zip(range(row , -1, -1) , range(col ,-1 , -1)):
        if board[i][j]==1:
            return False
    for i , j in zip(range(row , N ,1) , range(col , -1 ,-1)):
        if board[i][j]==1:
            return False
    return True


## Solution case for backtraking

In [7]:
def solve(board, col): 

    if col >= N: 
        return True
    for i in range(N): 
  
        if isSafe(board, i, col): 
            board[i][col] = 1
            if solve(board, col+1) == True: 
                return True
            board[i][col] = 0
    return False

## Function to start solving

In [8]:
def solveNQ(): 
    board = np.zeros((N,N) ,dtype = np.int8)
  
    if solve(board, 0) == False: 
        print ("Solution does not exist")
        return False
  
    print(board) 
    return True
   

In [9]:
solveNQ() 
#for 4queen problem

[[1 0 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]]


True

In [39]:
solveNQ() 
#for 8queen problem

[[1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]]


True